# When modifying this file, make sure to update on all repositories.  https://github.com/gruntwork-io/git-xargs can help with this.

name: Auto Labeler
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  apply_issue_label:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: 'Roadmap: None'
  apply_pull_request_label:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          LABELS: 'Roadmap: None'

