# When modifying this file, make sure to update on all repositories.  https://github.com/gruntwork-io/git-xargs can help with this.

name: Roadmap Auto Commenter
on:
  issues:
    types:
      # - labeled
      # - unlabeled
      - opened
  pull_request:
    types:
      # - labeled
      # - unlabeled
      - opened

# env:
#   MESSAGE: 'ROADMAP STATUS UPDATE:\n'

jobs:
  add_issue_comment:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    # concurrency:
    #   group: ${{ github.event.issue.number }}
    #   cancel-in-progress: true
    permissions:
      issues: write
      # actions: write
    steps:
      - name: add initial issue comment
        if: "${{ github.event.action == 'opened' && !contains(join(github.event.issue.labels.*.name), 'Roadmap:') }}"
        run: |
          gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            ROADMAP STATUS: This issue isn't currently on any roadmap.  Updates will be conveyed here as its place on/off a roadmap changes.

            You can view the roadmaps here: [Roadmaps Google Drive folder](https://drive.google.com/drive/folders/1Z6q2GoqnXIslxfcPP0ctVlTAKLi9OzEt).

      # - name: add issue comment roadmap programming short term
      #   if: "${{ github.event.action != 'opened' && github.event.action == 'labeled' && github.event.label.name == 'Roadmap: Programming - Short Term' }}"
      #   run: |
      #     gh issue comment "$NUMBER" --body "$BODY"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.issue.number }}
      #     BODY: >
      #       ROADMAP STATUS UPDATE: This issue has been added to the Short Term section of the [Programming Team Roadmap](https://docs.google.com/document/d/1xRSHEgf4jE4SRsx2Z5BX_uXKbJ7KuCW3v0ntugA76io).
      #
      # - name: remove issue comment roadmap programming short term
      #   if: "${{ github.event.action == 'unlabeled' && github.event.label.name == 'Roadmap: Programming - Short Term' }}"
      #   run: |
      #     gh issue comment "$NUMBER" --body "$BODY"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.issue.number }}
      #     BODY: >
      #       ROADMAP STATUS UPDATE: This issue has been removed from the Short Term section of the [Programming Team Roadmap](https://docs.google.com/document/d/1xRSHEgf4jE4SRsx2Z5BX_uXKbJ7KuCW3v0ntugA76io).
      #
      # - name: add issue comment no roadmap
      #   if: "${{ github.event.action == 'unlabeled' && contains(steps.*.conclusion, 'success') && !contains(join(github.event.issue.labels.*.name), 'Roadmap:') }}"
      #   run: |
      #     gh issue comment "$NUMBER" --body "$BODY"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.issue.number }}
      #     BODY: >
      #       ROADMAP STATUS UPDATE: This issue is no longer on any roadmap.
      #
      #       You can view the roadmaps here: [Roadmaps Google Drive folder](https://drive.google.com/drive/folders/1Z6q2GoqnXIslxfcPP0ctVlTAKLi9OzEt).

  add_pull_request_comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    # concurrency:
    #   group: ${{ github.event.number }}
    permissions:
      issues: write
      # actions: write
    steps:
      - name: add initial pull request comment
        if: "${{ github.event.action == 'opened' && !contains(join(github.event.pull_request.labels.*.name), 'Roadmap:') }}"
        run: |
          gh pr comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          BODY: >
            ROADMAP STATUS: This pull request isn't currently on any roadmap.  Updates will be conveyed here as its place on/off a roadmap changes.

            You can view the roadmaps here: [Roadmaps Google Drive folder](https://drive.google.com/drive/folders/1Z6q2GoqnXIslxfcPP0ctVlTAKLi9OzEt).

      # - name: add pull request comment no roadmap
      #   if: "${{ github.event.action == 'unlabeled' && !contains(join(github.event.pull_request.labels.*.name), 'Roadmap:') }}"
      #   run: |
      #     gh pr comment "$NUMBER" --body "$BODY"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.number }}
      #     BODY: >
      #       ROADMAP STATUS UPDATE: This pull request is no longer on any roadmap.
      #
      #       You can view the roadmaps here: [Roadmaps Google Drive folder](https://drive.google.com/drive/folders/1Z6q2GoqnXIslxfcPP0ctVlTAKLi9OzEt).
      #
      # - name: add pull request comment roadmap programming short term
      #   if: "${{ github.event.action == 'labeled' && github.event.label.name == 'Roadmap: Programming - Short Term' }}"
      #   run: |
      #     gh pr comment "$NUMBER" --body "$BODY"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.number }}
      #     BODY: >
      #       ROADMAP STATUS UPDATE: This issue has been added to the Short Term section of the [Programming Team Roadmap](https://docs.google.com/document/d/1xRSHEgf4jE4SRsx2Z5BX_uXKbJ7KuCW3v0ntugA76io).
      #
      # - name: remove pull request comment roadmap programming short term
      #   if: "${{ github.event.action == 'unlabeled' && github.event.label.name == 'Roadmap: Programming - Short Term' }}"
      #   run: |
      #     gh pr comment "$NUMBER" --body "$BODY"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.number }}
      #     BODY: >
      #       ROADMAP STATUS UPDATE: This issue has been removed from the Short Term section of the [Programming Team Roadmap](https://docs.google.com/document/d/1xRSHEgf4jE4SRsx2Z5BX_uXKbJ7KuCW3v0ntugA76io).
